name: Publish new version

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Choose version to bump"
        required: true
        default: "minor"
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"

jobs:
  publish:
    runs-on: ubuntu-latest

  steps:
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v3
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        npm version {{ github.event.inputs.target_env }}
        git push
