on: [pull_request, push]

jobs:
  test:
    name: Run tests & display coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn --non-interactive --frozen-lockfile --ignore-scripts

      - name: Run tests
        run: yarn test
